//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCrap.PolicyIntegration {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/Pursuit.PolicyIntegration.DataClasses")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebCrap.PolicyIntegration.Message[] MessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PolicyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PremiumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebCrap.PolicyIntegration.Message[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PolicyID {
            get {
                return this.PolicyIDField;
            }
            set {
                if ((this.PolicyIDField.Equals(value) != true)) {
                    this.PolicyIDField = value;
                    this.RaisePropertyChanged("PolicyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyNumber {
            get {
                return this.PolicyNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyNumberField, value) != true)) {
                    this.PolicyNumberField = value;
                    this.RaisePropertyChanged("PolicyNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Premium {
            get {
                return this.PremiumField;
            }
            set {
                if ((this.PremiumField.Equals(value) != true)) {
                    this.PremiumField = value;
                    this.RaisePropertyChanged("Premium");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/Pursuit.PolicyIntegration.DataClasses")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://schemas.datacontract.org/2004/07/Pursuit.PolicyIntegration.DataClasses")]
    [System.SerializableAttribute()]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebCrap.PolicyIntegration.BankingDetails BankingDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrokerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebCrap.PolicyIntegration.ClientDetails ClientDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommunicationTemplateTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebCrap.PolicyIntegration.Policy PolicyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UMCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebCrap.PolicyIntegration.BankingDetails BankingDetails {
            get {
                return this.BankingDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.BankingDetailsField, value) != true)) {
                    this.BankingDetailsField = value;
                    this.RaisePropertyChanged("BankingDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Broker {
            get {
                return this.BrokerField;
            }
            set {
                if ((object.ReferenceEquals(this.BrokerField, value) != true)) {
                    this.BrokerField = value;
                    this.RaisePropertyChanged("Broker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebCrap.PolicyIntegration.ClientDetails ClientDetails {
            get {
                return this.ClientDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientDetailsField, value) != true)) {
                    this.ClientDetailsField = value;
                    this.RaisePropertyChanged("ClientDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommunicationTemplateTitle {
            get {
                return this.CommunicationTemplateTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.CommunicationTemplateTitleField, value) != true)) {
                    this.CommunicationTemplateTitleField = value;
                    this.RaisePropertyChanged("CommunicationTemplateTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebCrap.PolicyIntegration.Policy Policy {
            get {
                return this.PolicyField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyField, value) != true)) {
                    this.PolicyField = value;
                    this.RaisePropertyChanged("Policy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UMCode {
            get {
                return this.UMCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UMCodeField, value) != true)) {
                    this.UMCodeField = value;
                    this.RaisePropertyChanged("UMCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankingDetails", Namespace="http://schemas.datacontract.org/2004/07/Pursuit.PolicyIntegration.DataClasses")]
    [System.SerializableAttribute()]
    public partial class BankingDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountHolderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CollectionDayField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountHolder {
            get {
                return this.AccountHolderField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountHolderField, value) != true)) {
                    this.AccountHolderField = value;
                    this.RaisePropertyChanged("AccountHolder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountType {
            get {
                return this.AccountTypeField;
            }
            set {
                if ((this.AccountTypeField.Equals(value) != true)) {
                    this.AccountTypeField = value;
                    this.RaisePropertyChanged("AccountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchCode {
            get {
                return this.BranchCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchCodeField, value) != true)) {
                    this.BranchCodeField = value;
                    this.RaisePropertyChanged("BranchCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CollectionDay {
            get {
                return this.CollectionDayField;
            }
            set {
                if ((this.CollectionDayField.Equals(value) != true)) {
                    this.CollectionDayField = value;
                    this.RaisePropertyChanged("CollectionDay");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientDetails", Namespace="http://schemas.datacontract.org/2004/07/Pursuit.PolicyIntegration.DataClasses")]
    [System.SerializableAttribute()]
    public partial class ClientDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebCrap.PolicyIntegration.AddressDetails AddressDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebCrap.PolicyIntegration.Category[] CategoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebCrap.PolicyIntegration.CommunicationMethod CommunicationMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyEmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyTelNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebCrap.PolicyIntegration.AddressDetails AddressDetails {
            get {
                return this.AddressDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressDetailsField, value) != true)) {
                    this.AddressDetailsField = value;
                    this.RaisePropertyChanged("AddressDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebCrap.PolicyIntegration.Category[] Categories {
            get {
                return this.CategoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriesField, value) != true)) {
                    this.CategoriesField = value;
                    this.RaisePropertyChanged("Categories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CellNumber {
            get {
                return this.CellNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CellNumberField, value) != true)) {
                    this.CellNumberField = value;
                    this.RaisePropertyChanged("CellNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebCrap.PolicyIntegration.CommunicationMethod CommunicationMethod {
            get {
                return this.CommunicationMethodField;
            }
            set {
                if ((this.CommunicationMethodField.Equals(value) != true)) {
                    this.CommunicationMethodField = value;
                    this.RaisePropertyChanged("CommunicationMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyEmailAddress {
            get {
                return this.CompanyEmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyEmailAddressField, value) != true)) {
                    this.CompanyEmailAddressField = value;
                    this.RaisePropertyChanged("CompanyEmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyTelNumber {
            get {
                return this.CompanyTelNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyTelNumberField, value) != true)) {
                    this.CompanyTelNumberField = value;
                    this.RaisePropertyChanged("CompanyTelNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdNumber {
            get {
                return this.IdNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IdNumberField, value) != true)) {
                    this.IdNumberField = value;
                    this.RaisePropertyChanged("IdNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegNumber {
            get {
                return this.RegNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RegNumberField, value) != true)) {
                    this.RegNumberField = value;
                    this.RaisePropertyChanged("RegNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Policy", Namespace="http://schemas.datacontract.org/2004/07/Pursuit.PolicyIntegration.DataClasses")]
    [System.SerializableAttribute()]
    public partial class Policy : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InceptionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentFrequencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebCrap.PolicyIntegration.RiskDetail[] RiskDetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InceptionDate {
            get {
                return this.InceptionDateField;
            }
            set {
                if ((this.InceptionDateField.Equals(value) != true)) {
                    this.InceptionDateField = value;
                    this.RaisePropertyChanged("InceptionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentFrequency {
            get {
                return this.PaymentFrequencyField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentFrequencyField, value) != true)) {
                    this.PaymentFrequencyField = value;
                    this.RaisePropertyChanged("PaymentFrequency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebCrap.PolicyIntegration.RiskDetail[] RiskDetails {
            get {
                return this.RiskDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.RiskDetailsField, value) != true)) {
                    this.RiskDetailsField = value;
                    this.RaisePropertyChanged("RiskDetails");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressDetails", Namespace="http://schemas.datacontract.org/2004/07/Pursuit.PolicyIntegration.DataClasses")]
    [System.SerializableAttribute()]
    public partial class AddressDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhysicalAddress1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhysicalAddress2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhysicalCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhysicalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhysicalSuburbField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhysicalAddress1 {
            get {
                return this.PhysicalAddress1Field;
            }
            set {
                if ((object.ReferenceEquals(this.PhysicalAddress1Field, value) != true)) {
                    this.PhysicalAddress1Field = value;
                    this.RaisePropertyChanged("PhysicalAddress1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhysicalAddress2 {
            get {
                return this.PhysicalAddress2Field;
            }
            set {
                if ((object.ReferenceEquals(this.PhysicalAddress2Field, value) != true)) {
                    this.PhysicalAddress2Field = value;
                    this.RaisePropertyChanged("PhysicalAddress2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhysicalCity {
            get {
                return this.PhysicalCityField;
            }
            set {
                if ((object.ReferenceEquals(this.PhysicalCityField, value) != true)) {
                    this.PhysicalCityField = value;
                    this.RaisePropertyChanged("PhysicalCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhysicalCode {
            get {
                return this.PhysicalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PhysicalCodeField, value) != true)) {
                    this.PhysicalCodeField = value;
                    this.RaisePropertyChanged("PhysicalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhysicalSuburb {
            get {
                return this.PhysicalSuburbField;
            }
            set {
                if ((object.ReferenceEquals(this.PhysicalSuburbField, value) != true)) {
                    this.PhysicalSuburbField = value;
                    this.RaisePropertyChanged("PhysicalSuburb");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/Pursuit.PolicyIntegration.DataClasses")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer {
            get {
                return this.AnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerField, value) != true)) {
                    this.AnswerField = value;
                    this.RaisePropertyChanged("Answer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Question {
            get {
                return this.QuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionField, value) != true)) {
                    this.QuestionField = value;
                    this.RaisePropertyChanged("Question");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommunicationMethod", Namespace="http://schemas.datacontract.org/2004/07/Pursuit.PolicyIntegration.DataClasses")]
    public enum CommunicationMethod : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mobile = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Email = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmailWithAttachments = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RiskDetail", Namespace="http://schemas.datacontract.org/2004/07/Pursuit.PolicyIntegration.DataClasses")]
    [System.SerializableAttribute()]
    public partial class RiskDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoverNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebCrap.PolicyIntegration.Factor[] FactorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PremiumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SumInsuredField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CoverName {
            get {
                return this.CoverNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CoverNameField, value) != true)) {
                    this.CoverNameField = value;
                    this.RaisePropertyChanged("CoverName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebCrap.PolicyIntegration.Factor[] Factors {
            get {
                return this.FactorsField;
            }
            set {
                if ((object.ReferenceEquals(this.FactorsField, value) != true)) {
                    this.FactorsField = value;
                    this.RaisePropertyChanged("Factors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Premium {
            get {
                return this.PremiumField;
            }
            set {
                if ((this.PremiumField.Equals(value) != true)) {
                    this.PremiumField = value;
                    this.RaisePropertyChanged("Premium");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SumInsured {
            get {
                return this.SumInsuredField;
            }
            set {
                if ((this.SumInsuredField.Equals(value) != true)) {
                    this.SumInsuredField = value;
                    this.RaisePropertyChanged("SumInsured");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Factor", Namespace="http://schemas.datacontract.org/2004/07/Pursuit.PolicyIntegration.DataClasses")]
    [System.SerializableAttribute()]
    public partial class Factor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer {
            get {
                return this.AnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerField, value) != true)) {
                    this.AnswerField = value;
                    this.RaisePropertyChanged("Answer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Question {
            get {
                return this.QuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionField, value) != true)) {
                    this.QuestionField = value;
                    this.RaisePropertyChanged("Question");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankNames", Namespace="http://schemas.datacontract.org/2004/07/Pursuit.PolicyIntegration.DataClasses")]
    [System.SerializableAttribute()]
    public partial class BankNames : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebCrap.PolicyIntegration.Bank[] BanksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebCrap.PolicyIntegration.Message[] MessagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebCrap.PolicyIntegration.Bank[] Banks {
            get {
                return this.BanksField;
            }
            set {
                if ((object.ReferenceEquals(this.BanksField, value) != true)) {
                    this.BanksField = value;
                    this.RaisePropertyChanged("Banks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebCrap.PolicyIntegration.Message[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bank", Namespace="http://schemas.datacontract.org/2004/07/Pursuit.PolicyIntegration.DataClasses")]
    [System.SerializableAttribute()]
    public partial class Bank : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankName {
            get {
                return this.BankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNameField, value) != true)) {
                    this.BankNameField = value;
                    this.RaisePropertyChanged("BankName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BranchNames", Namespace="http://schemas.datacontract.org/2004/07/Pursuit.PolicyIntegration.DataClasses")]
    [System.SerializableAttribute()]
    public partial class BranchNames : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebCrap.PolicyIntegration.Branch[] BranchesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebCrap.PolicyIntegration.Message[] MessagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebCrap.PolicyIntegration.Branch[] Branches {
            get {
                return this.BranchesField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchesField, value) != true)) {
                    this.BranchesField = value;
                    this.RaisePropertyChanged("Branches");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebCrap.PolicyIntegration.Message[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Branch", Namespace="http://schemas.datacontract.org/2004/07/Pursuit.PolicyIntegration.DataClasses")]
    [System.SerializableAttribute()]
    public partial class Branch : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchCode {
            get {
                return this.BranchCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchCodeField, value) != true)) {
                    this.BranchCodeField = value;
                    this.RaisePropertyChanged("BranchCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchName {
            get {
                return this.BranchNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchNameField, value) != true)) {
                    this.BranchNameField = value;
                    this.RaisePropertyChanged("BranchName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankAccountTypes", Namespace="http://schemas.datacontract.org/2004/07/Pursuit.PolicyIntegration.DataClasses")]
    [System.SerializableAttribute()]
    public partial class BankAccountTypes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebCrap.PolicyIntegration.BankAccountType[] AccountTypesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebCrap.PolicyIntegration.Message[] MessagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebCrap.PolicyIntegration.BankAccountType[] AccountTypes {
            get {
                return this.AccountTypesField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountTypesField, value) != true)) {
                    this.AccountTypesField = value;
                    this.RaisePropertyChanged("AccountTypes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebCrap.PolicyIntegration.Message[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankAccountType", Namespace="http://schemas.datacontract.org/2004/07/Pursuit.PolicyIntegration.DataClasses")]
    [System.SerializableAttribute()]
    public partial class BankAccountType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountCode {
            get {
                return this.AccountCodeField;
            }
            set {
                if ((this.AccountCodeField.Equals(value) != true)) {
                    this.AccountCodeField = value;
                    this.RaisePropertyChanged("AccountCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountType {
            get {
                return this.AccountTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountTypeField, value) != true)) {
                    this.AccountTypeField = value;
                    this.RaisePropertyChanged("AccountType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PolicyIntegration.IPolicyIntegration")]
    public interface IPolicyIntegration {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyIntegration/IDCheckAjax", ReplyAction="http://tempuri.org/IPolicyIntegration/IDCheckAjaxResponse")]
        WebCrap.PolicyIntegration.Response IDCheckAjax(string idNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyIntegration/IDCheckAjax", ReplyAction="http://tempuri.org/IPolicyIntegration/IDCheckAjaxResponse")]
        System.Threading.Tasks.Task<WebCrap.PolicyIntegration.Response> IDCheckAjaxAsync(string idNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyIntegration/IDCheck", ReplyAction="http://tempuri.org/IPolicyIntegration/IDCheckResponse")]
        WebCrap.PolicyIntegration.Response IDCheck(string idNumber, string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyIntegration/IDCheck", ReplyAction="http://tempuri.org/IPolicyIntegration/IDCheckResponse")]
        System.Threading.Tasks.Task<WebCrap.PolicyIntegration.Response> IDCheckAsync(string idNumber, string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyIntegration/GeneratePolicy", ReplyAction="http://tempuri.org/IPolicyIntegration/GeneratePolicyResponse")]
        WebCrap.PolicyIntegration.Response GeneratePolicy(WebCrap.PolicyIntegration.Request request, string campaignName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyIntegration/GeneratePolicy", ReplyAction="http://tempuri.org/IPolicyIntegration/GeneratePolicyResponse")]
        System.Threading.Tasks.Task<WebCrap.PolicyIntegration.Response> GeneratePolicyAsync(WebCrap.PolicyIntegration.Request request, string campaignName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyIntegration/RetrieveBanks", ReplyAction="http://tempuri.org/IPolicyIntegration/RetrieveBanksResponse")]
        WebCrap.PolicyIntegration.BankNames RetrieveBanks(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyIntegration/RetrieveBanks", ReplyAction="http://tempuri.org/IPolicyIntegration/RetrieveBanksResponse")]
        System.Threading.Tasks.Task<WebCrap.PolicyIntegration.BankNames> RetrieveBanksAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyIntegration/RetrieveBranches", ReplyAction="http://tempuri.org/IPolicyIntegration/RetrieveBranchesResponse")]
        WebCrap.PolicyIntegration.BranchNames RetrieveBranches(string bankName, string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyIntegration/RetrieveBranches", ReplyAction="http://tempuri.org/IPolicyIntegration/RetrieveBranchesResponse")]
        System.Threading.Tasks.Task<WebCrap.PolicyIntegration.BranchNames> RetrieveBranchesAsync(string bankName, string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyIntegration/RetrieveBankAccountTypes", ReplyAction="http://tempuri.org/IPolicyIntegration/RetrieveBankAccountTypesResponse")]
        WebCrap.PolicyIntegration.BankAccountTypes RetrieveBankAccountTypes(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyIntegration/RetrieveBankAccountTypes", ReplyAction="http://tempuri.org/IPolicyIntegration/RetrieveBankAccountTypesResponse")]
        System.Threading.Tasks.Task<WebCrap.PolicyIntegration.BankAccountTypes> RetrieveBankAccountTypesAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyIntegration/GeneratePolicySchedule", ReplyAction="http://tempuri.org/IPolicyIntegration/GeneratePolicyScheduleResponse")]
        string GeneratePolicySchedule(System.Guid policyID, string umCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyIntegration/GeneratePolicySchedule", ReplyAction="http://tempuri.org/IPolicyIntegration/GeneratePolicyScheduleResponse")]
        System.Threading.Tasks.Task<string> GeneratePolicyScheduleAsync(System.Guid policyID, string umCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyIntegration/CDVCheck", ReplyAction="http://tempuri.org/IPolicyIntegration/CDVCheckResponse")]
        bool CDVCheck(int accountType, string accountNumber, string branchCode, string UMCode, string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyIntegration/CDVCheck", ReplyAction="http://tempuri.org/IPolicyIntegration/CDVCheckResponse")]
        System.Threading.Tasks.Task<bool> CDVCheckAsync(int accountType, string accountNumber, string branchCode, string UMCode, string userName, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPolicyIntegrationChannel : WebCrap.PolicyIntegration.IPolicyIntegration, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PolicyIntegrationClient : System.ServiceModel.ClientBase<WebCrap.PolicyIntegration.IPolicyIntegration>, WebCrap.PolicyIntegration.IPolicyIntegration {
        
        public PolicyIntegrationClient() {
        }
        
        public PolicyIntegrationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PolicyIntegrationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PolicyIntegrationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PolicyIntegrationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebCrap.PolicyIntegration.Response IDCheckAjax(string idNumber) {
            return base.Channel.IDCheckAjax(idNumber);
        }
        
        public System.Threading.Tasks.Task<WebCrap.PolicyIntegration.Response> IDCheckAjaxAsync(string idNumber) {
            return base.Channel.IDCheckAjaxAsync(idNumber);
        }
        
        public WebCrap.PolicyIntegration.Response IDCheck(string idNumber, string userName, string password) {
            return base.Channel.IDCheck(idNumber, userName, password);
        }
        
        public System.Threading.Tasks.Task<WebCrap.PolicyIntegration.Response> IDCheckAsync(string idNumber, string userName, string password) {
            return base.Channel.IDCheckAsync(idNumber, userName, password);
        }
        
        public WebCrap.PolicyIntegration.Response GeneratePolicy(WebCrap.PolicyIntegration.Request request, string campaignName) {
            return base.Channel.GeneratePolicy(request, campaignName);
        }
        
        public System.Threading.Tasks.Task<WebCrap.PolicyIntegration.Response> GeneratePolicyAsync(WebCrap.PolicyIntegration.Request request, string campaignName) {
            return base.Channel.GeneratePolicyAsync(request, campaignName);
        }
        
        public WebCrap.PolicyIntegration.BankNames RetrieveBanks(string userName, string password) {
            return base.Channel.RetrieveBanks(userName, password);
        }
        
        public System.Threading.Tasks.Task<WebCrap.PolicyIntegration.BankNames> RetrieveBanksAsync(string userName, string password) {
            return base.Channel.RetrieveBanksAsync(userName, password);
        }
        
        public WebCrap.PolicyIntegration.BranchNames RetrieveBranches(string bankName, string userName, string password) {
            return base.Channel.RetrieveBranches(bankName, userName, password);
        }
        
        public System.Threading.Tasks.Task<WebCrap.PolicyIntegration.BranchNames> RetrieveBranchesAsync(string bankName, string userName, string password) {
            return base.Channel.RetrieveBranchesAsync(bankName, userName, password);
        }
        
        public WebCrap.PolicyIntegration.BankAccountTypes RetrieveBankAccountTypes(string userName, string password) {
            return base.Channel.RetrieveBankAccountTypes(userName, password);
        }
        
        public System.Threading.Tasks.Task<WebCrap.PolicyIntegration.BankAccountTypes> RetrieveBankAccountTypesAsync(string userName, string password) {
            return base.Channel.RetrieveBankAccountTypesAsync(userName, password);
        }
        
        public string GeneratePolicySchedule(System.Guid policyID, string umCode) {
            return base.Channel.GeneratePolicySchedule(policyID, umCode);
        }
        
        public System.Threading.Tasks.Task<string> GeneratePolicyScheduleAsync(System.Guid policyID, string umCode) {
            return base.Channel.GeneratePolicyScheduleAsync(policyID, umCode);
        }
        
        public bool CDVCheck(int accountType, string accountNumber, string branchCode, string UMCode, string userName, string password) {
            return base.Channel.CDVCheck(accountType, accountNumber, branchCode, UMCode, userName, password);
        }
        
        public System.Threading.Tasks.Task<bool> CDVCheckAsync(int accountType, string accountNumber, string branchCode, string UMCode, string userName, string password) {
            return base.Channel.CDVCheckAsync(accountType, accountNumber, branchCode, UMCode, userName, password);
        }
    }
}
